In [1]:
import numpy as np
import pandas as pd

In [132]:
# generate time series df with popularity rating
datasetname = "falcon9--2018-02-01--2019-07-01.csv"
filepath = "./datasets/" + datasetname

In [219]:
def getFrequency(dataset_name):
    filepath = "./datasets/" + datasetname
    
    dataset_df = pd.read_csv(filepath)
    params = dataset_name[:-4].split('--')
    date_df = pd.Series(0, index=pd.date_range(params[1], params[2]))
    
    filtered_dates = dataset_df.loc[:, ['date']]
    filtered_dates = filtered_dates.apply(lambda x: pd.to_datetime(x).dt.normalize())    
    counts = filtered_dates.groupby('date').size()
    
    # merge dates and counts, so that we have all dates
    counts = (counts + date_df).fillna(0)

    return dataset_df, counts

def normalizeFrequency(freqs):
    # min-max feature scaling to get values between 0 and 1
    freqs_norm = (freqs - freqs.min()) / (freqs.max() - freqs.min())
    return freqs_norm

def getTopPostFromDate(dataset_df, date):
    # grab tweets from most active day
    data_df.loc[:, 'date'] = data_df.loc[:, 'date'].apply(lambda x: pd.to_datetime(x).normalize())
    top_df = data_df.groupby(by='date').get_group(pd.Timestamp(2019,5,24))
    
    top_df = top_df.sort_values('favorites', ascending=False)
    
    return top_df

In [221]:
# display frequency of dataset
data_df, freqs = getFrequency(datasetname)
freqs

2018-01-31    0.0
2018-02-01    2.0
2018-02-02    2.0
2018-02-03    0.0
2018-02-04    0.0
2018-02-05    0.0
2018-02-06    6.0
2018-02-07    1.0
2018-02-08    1.0
2018-02-09    1.0
2018-02-10    0.0
2018-02-11    0.0
2018-02-12    0.0
2018-02-13    0.0
2018-02-14    0.0
2018-02-15    0.0
2018-02-16    0.0
2018-02-17    0.0
2018-02-18    0.0
2018-02-19    0.0
2018-02-20    0.0
2018-02-21    0.0
2018-02-22    2.0
2018-02-23    0.0
2018-02-24    0.0
2018-02-25    0.0
2018-02-26    1.0
2018-02-27    0.0
2018-02-28    1.0
2018-03-01    0.0
             ...
2019-06-02    0.0
2019-06-03    0.0
2019-06-04    0.0
2019-06-05    0.0
2019-06-06    0.0
2019-06-07    0.0
2019-06-08    0.0
2019-06-09    0.0
2019-06-10    0.0
2019-06-11    0.0
2019-06-12    0.0
2019-06-13    0.0
2019-06-14    0.0
2019-06-15    0.0
2019-06-16    0.0
2019-06-17    0.0
2019-06-18    0.0
2019-06-19    0.0
2019-06-20    0.0
2019-06-21    0.0
2019-06-22    0.0
2019-06-23    0.0
2019-06-24    0.0
2019-06-25    0.0
2019-06-26    0.0
2019-06-27    0.0
2019-06-28    0.0
2019-06-29    0.0
2019-06-30    0.0
2019-07-01    0.0
Length: 517, dtype: float64

In [222]:
# display normalized frequency
freqs_norm = normalizeFrequency(freqs)
freqs_norm

2018-01-31    0.000000
2018-02-01    0.014184
2018-02-02    0.014184
2018-02-03    0.000000
2018-02-04    0.000000
2018-02-05    0.000000
2018-02-06    0.042553
2018-02-07    0.007092
2018-02-08    0.007092
2018-02-09    0.007092
2018-02-10    0.000000
2018-02-11    0.000000
2018-02-12    0.000000
2018-02-13    0.000000
2018-02-14    0.000000
2018-02-15    0.000000
2018-02-16    0.000000
2018-02-17    0.000000
2018-02-18    0.000000
2018-02-19    0.000000
2018-02-20    0.000000
2018-02-21    0.000000
2018-02-22    0.014184
2018-02-23    0.000000
2018-02-24    0.000000
2018-02-25    0.000000
2018-02-26    0.007092
2018-02-27    0.000000
2018-02-28    0.007092
2018-03-01    0.000000
                ...
2019-06-02    0.000000
2019-06-03    0.000000
2019-06-04    0.000000
2019-06-05    0.000000
2019-06-06    0.000000
2019-06-07    0.000000
2019-06-08    0.000000
2019-06-09    0.000000
2019-06-10    0.000000
2019-06-11    0.000000
2019-06-12    0.000000
2019-06-13    0.000000
2019-06-14    0.000000
2019-06-15    0.000000
2019-06-16    0.000000
2019-06-17    0.000000
2019-06-18    0.000000
2019-06-19    0.000000
2019-06-20    0.000000
2019-06-21    0.000000
2019-06-22    0.000000
2019-06-23    0.000000
2019-06-24    0.000000
2019-06-25    0.000000
2019-06-26    0.000000
2019-06-27    0.000000
2019-06-28    0.000000
2019-06-29    0.000000
2019-06-30    0.000000
2019-07-01    0.000000
Length: 517, dtype: float64

In [223]:
# display most active day
print("Day with most Tweets: %s, %d" % (str(freqs.idxmax()), freqs.max()))

# get most popular tweets from that day
getTopPostFromDate(data_df, freqs.idxmax())

Day with most Tweets: 2019-05-23 00:00:00, 141

,username,user_handle,date,retweets,favorites,text,geological_location,mentions,hashtags,tweet_id,permalink
4,Michael Baylor,nextspaceflight,2019-05-24,307,1267,#Starlink passes over the Netherlands after la...,NaN,@jelhoo1bf4,#Starlink #SpaceX #Falcon9,1132073019071877120,https://twitter.com/nextspaceflight/status/113...
3,Dr.DahaNoob (Denise K.),Mimikry_,2019-05-24,34,240,Finally here my clean shot from yesterdays #Sp...,NaN,NaN,#SpaceX #Falcon9 #Starlink,1132092811489230848,https://twitter.com/Mimikry_/status/1132092811...
22,Erik Kuna ðŸš€,erikkuna,2019-05-24,26,182,Ever wonder what it would look like to watch a...,NaN,@erikkuna @superclusterhq @superclusterhq,#SpaceX #Falcon9 #spaceisforeveryone,1132043762572636161,https://twitter.com/erikkuna/status/1132043762...
11,Marcus Cote,marcuscotephoto,2019-05-24,22,171,Through the lightning tower-- #Falcon9 lifts f...,NaN,@marcuscotephoto,#Falcon9 #OCISLY #Starlink #SpaceX,1131913831440146434,https://twitter.com/marcuscotephoto/status/113...
10,ðŸ—£Eric DeSalvo,EricDeSalvo,2019-05-24,6,139,Blastoff views from the heart of Orlando #Falc...,NaN,NaN,#Falcon9,1131947137091162112,https://twitter.com/EricDeSalvo/status/1131947...
8,Richard,RDAnglePhoto,2019-05-24,35,124,My views of last nights @SpaceX #Falcon9 launc...,NaN,@SpaceX @elonmusk,#Falcon9 #Starlink #SpaceX,1131976440952565761,https://twitter.com/RDAnglePhoto/status/113197...
9,Flight Club,flightclubio,2019-05-24,13,57,My #Falcon9 S2 model is underpowered It was al...,NaN,@Erdayastronaut @elonmusk @934kN,#Falcon9 #Starlink,1131970182640013312,https://twitter.com/flightclubio/status/113197...
2,Diana Halstead,DianaHalstead,2019-05-24,9,53,Success! @SpaceX Falcon9 Starlink! #SpaceX #Fa...,NaN,@SpaceX,#SpaceX #Falcon9 #Starlink #NASA #NASASocial,1132122553647083521,https://twitter.com/DianaHalstead/status/11321...
6,Thomas Burghardt,TGMetsFan98,2019-05-24,5,32,Replay: @SpaceX #Falcon9 launches the first 60...,NaN,@SpaceX,#Falcon9 #Starlink,1132016434152919047,https://twitter.com/TGMetsFan98/status/1132016...
7,LaunchLife,YourLaunchLife,2019-05-24,3,27,Weâ€™ll be doing a blog post of your Starlink la...,NaN,NaN,#falcon9 #starlink #launchlife,1131986653747134464,https://twitter.com/YourLaunchLife/status/1131...
5,Lyfe B. Wilde,ArrogantWatcher,2019-05-24,6,24,THE SPACE COAST #Falcon9 @spacex pic.twitter.c...,NaN,@spacex,#Falcon9,1132059522485432321,https://twitter.com/ArrogantWatcher/status/113...
59,Katya Pavlushchenko,katlinegrey,2019-05-24,1,19,"Well, and of course #Rogozin couldn't resist t...",NaN,@elonmusk,#Rogozin #Falcon9,1131838010415300608,https://twitter.com/katlinegrey/status/1131838...
23,Altaira,JrAstronautin,2019-05-24,3,13,We have LIFTOFF! GO #Falcon9! Go #Starlink! ht...,NaN,NaN,#Falcon9 #Starlink,1131852656773873664,https://twitter.com/JrAstronautin/status/11318...
41,The Talk of Titusville ðŸš€ðŸŒ´ðŸŒŽðŸŒ•,TalkofTville,2019-05-24,0,2,@SpaceX #Falcon9 fairings successfully recover...,NaN,@SpaceX,#Falcon9 #StarLink,1132005217229266945,https://twitter.com/TalkofTville/status/113200...